// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

// PRGRedirect renders a script that replaces the browser URL via history.replaceState.
// This implements the Post/Redirect/Get pattern for HTMX forms: after a successful
// POST, the browser URL is updated so that a page refresh performs a GET to the
// result page instead of resubmitting the form.
func PRGRedirect(url string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if url != "" {
			templ_7745c5c3_Err = prgReplaceURL(url).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// prgReplaceURL replaces the current browser URL without triggering navigation.
func prgReplaceURL(url string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_prgReplaceURL_dbf4`,
		Function: `function __templ_prgReplaceURL_dbf4(url){history.replaceState(null, '', url);
}`,
		Call:       templ.SafeScript(`__templ_prgReplaceURL_dbf4`, url),
		CallInline: templ.SafeScriptInline(`__templ_prgReplaceURL_dbf4`, url),
	}
}

var _ = templruntime.GeneratedTemplate
